### ISSUE TITLE
Payment cannot be made if store currency is in Sats

### ISSUE THREAD

**Issue by Satoshi55** [lnbits/lnbits-bitcoin-onchain-and-lightning-payment-gateway#3]
If the store currency is in Satoshis (Sats), the plugin makes a call to blockchain.info to get a price in Sats, the blockchain.info API returns a string resulting in a 500 error in the plugin.

Issue seems similar to this one: https://gitlab.com/sovereign-individuals/lnbits-for-woocommerce/-/issues/2
![Error Checkout in Sats](https://user-images.githubusercontent.com/116438199/197338569-afbc1444-6250-4089-ba15-86846819ae24.jpg)

**Comment by Satoshi55** [comment]
Just fixed it by changing the following the code:
```
class Utils {
    public static function convert_to_satoshis($amount, $currency) {
        if(strtolower($currency) !== 'sat') {
            error_log($amount . " " . $currency);
            $c    = new CurlWrapper();
            $resp = $c->get('https://blockchain.info/tobtc', array(
                'currency' => $currency,
                'value'    => $amount
            ), array());

            if ($resp['status'] != 200) {
                throw new \Exception('Blockchain.info request for currency conversion failed. Got status ' . $resp['status']);
            }

            return (int) round($resp['response'] * 1);
        }
        else {
            return intval($amount * 1);
        }
    }
}
```
BTW: I wasn't aware currency 'Sats' is not available by default in WooCommerce. I was able to choose this currency because I did also install 'BTCPay For Woocommerce V2' with 'Sats-Mode' enabled. Sats-Mode: 'Makes Satoshis/Sats available as currency "SAT" (can be found in WooCommerce->Settings->General) and handles conversion to BTC before creating the invoice on BTCPay.'

**Comment by blackcoffeexbt** [comment]
Thanks for the bug report @Satoshi55 . It seems to be an edge case when both BTCPay and LNbits plugins are installed and the store currency is set to "sats". Is that correct?

I've updated the plugin to handle this case. Will update the plugin on WordPress.com after testing.

**Comment by Satoshi55** [comment]
Yes, that's correct @blackcoffeexbt . Thank you.
